services:
  liveserver:
    image: tiangolo/nginx-rtmp:latest-2024-12-02
    container_name: liveserver
    networks:
      - worker_dev
    volumes:
      - ./WorkerApi/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "1935:1935"
      - "8080:80"

  workerapi:
    image: ${DOCKER_REGISTRY-}workerapi
    networks:
      - worker_dev
    environment:
      AMIYA_API: http://01.ai.falafel.stream:5000/eval
      AMIYA_OUTJPG: /tmp/amiya-out.jpg
    build:
      context: .
      dockerfile: WorkerApi/Dockerfile
    ports:
    - "5000:5000"

networks:
  worker_dev:
    driver: bridge
