services:
  liveserver:
    image: tiangolo/nginx-rtmp:latest-2024-12-02
    container_name: liveserver
    networks:
      - worker_dev
    volumes:
      - ./WorkerApi/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "1935:1935"
      - "8080:80"

  workerapi:
    image: ${DOCKER_REGISTRY-}workerapi
    networks:
      - worker_dev
    build:
      context: .
      dockerfile: WorkerApi/Dockerfile
    ports:
    - "5000:5000"

networks:
  worker_dev:
    driver: bridge
