@WorkerApi_HostAddress = https://localhost:51046

GET {{WorkerApi_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{WorkerApi_HostAddress}}/worker/
Accept: application/json
Content-Type: application/json
{"jsonWorkerConfiguration":"{\"1\":{\"type\":\"_IN\",\"properties\":{\"src\":\"rtmp://liveserver:1935/live1/test\"},\"in\":[],\"out\":[\"e1-3\",\"eaa1-3\"]},\"2\":{\"type\":\"_OUT\",\"properties\":{\"dst\":\"rtmp://liveserver:1935/live2/test\"},\"in\":[\"e3-2\",\"eaa1-3\"],\"out\":[]},\"3\":{\"type\":\"drawbox\",\"properties\":{\"color\":\"#000000\",\"top\":0,\"bottom\":0,\"left\":0,\"right\":0,\"thickness\":1},\"in\":[\"e1-3\"],\"out\":[\"e3-2\"]}}"}


### TEST FROM Front
POST {{WorkerApi_HostAddress}}/worker/
Accept: application/json
Content-Type: application/json
{"1":{"type":"_IN","properties":{"src":""},"in":[],"out":["e1-3",null]},"2":{"type":"_OUT","properties":{"dst":""},"in":["e3-2",null],"out":[]},"3":{"type":"drawbox","properties":{"color":"#000000","top":0,"bottom":0,"left":0,"right":0,"thickness":1},"in":["e1-3"],"out":["e3-2"]}}